apiVersion: v1
kind: Pod
metadata:
  name: copy-pod
  namespace: keycloak # Replace with your namespace
spec:
  containers:
    - name: copy-container
      image: busybox:latest # Or any image with basic utilities like cp
      command: ["/bin/sh", "-c", "sleep 3600"] # Keep the pod running for a while
      volumeMounts:
        - name: extensions # Must match the volume name
          mountPath: /mnt/extensions
  volumes:
    - name: extensions # Must match the volumeMount name
      persistentVolumeClaim:
        claimName: extensions